- name: Upload new code and ReStart the service
  hosts: localhost:90
  vars:
    app: httpd

  tasks:
    - name: Place custom HTML File
      copy:
        src: /var/lib/jenkins/workspace/website-update/index.html
        dest: /var/www/html/index.html
      become: true

    - name: Start the service
      service:
        name: httpd
        state: restarted
        enabled: yes
      become: true
